version: "3"
services:
  web:
    build: .
    links: 
      - db
    depends_on:
      - db
    image: photo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    command: bash -c "sleep 5; npm start"
    restart: on-failure
    ports: 
      - 1337:1337
    networks:
      - webnet
  # prox:
  #   image: amaz-prox
  #   restart: on-failure
  #   ports:
  #     - 3003:3003
  db:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: photos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data
    networks:
      - webnet
    ports:
      - 27017:27017
  seed:
    build: ../../csvs
    links:
      - db
volumes: 
  mongo-data:
networks:
  webnet: